Resources:
  lzVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      InstanceTenancy: default
      EnableDnsHostnames: false
      Tags:
        - Value: cos-lz-vpc
          Key: Name
Outputs:
  VPCID:
    Description: The ID of the VPC
    Value: !Ref lzVPC